# -*- coding: utf-8 -*-
"""Scraping RONB

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11KjXddclQfdVGuT-r2zi7KOMYTgvo-nH
"""

!pip install ntscraper

import pandas as pd
from ntscraper import Nitter

scraper = Nitter()

def RONB(name,modes):
  tweets = scraper.get_tweets(name,mode=modes)
  final_tweets = []
  for tweet in tweets['tweets']:
    data  = [tweet['link'],tweet['text'],tweet['date'],tweet['stats']['comments'],tweet['stats']['retweets'],tweet['stats']['quotes'],tweet['stats']['likes'],tweet['pictures']]
    final_tweets.append(data)
  data = pd.DataFrame(final_tweets,columns=['link','text','date','NoOfComments','NoOfRetweets','NoOfQuotes','NoOfLikes','LinkToPicture'])
  return data

data = RONB('RONBupdates','user')

data

data.to_csv('data_RONB.csv')

